export const data = [
  {
    category: "خواتم",
    slug: "rings",
    array: [
      {
        id: 1,
        new: "جديد",
        imgName: "photo/ring1.webp",
        title: "تباين جريء بين الذهب الوردي والماس الداكن",
        disc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
        price: "7250,00",
      },
      {
        id: 2,
        imgName: "photo/ring2.webp",
        title: "أناقة كلاسيكية بحبّة لؤلؤ طبيعية",
        disc: "Hic autem sint, soluta deserunt temporibus rem facere,",
        price: 5500.0,
      },
      {
        id: 3,
        new: "جديد",
        imgName: "photo/ring3.webp",
        title: "فضّة مصقولة مع حجر مُقزّح كالضوء القمري",
        disc: "Officia, optio corrupti numquam vel expedita praesentium.",
        price: 25000.0,
      },
      {
        id: 4,
        new: "جديد",
        imgName: "photo/ring4.webp",
        title: "نقش وردي ثلاثي الأبعاد بطلاء مينا ناعم",
        disc: "Officia, optio corrupti numquam vel expedita praesentium.",
        price: 25000.0,
      },
      {
        id: 5,
        imgName: "photo/ring5.webp",
        title: "حجر مركزي مقطوع على شكل نجمة مع هالة براقة",
        disc: "Officia, optio corrupti numquam vel expedita praesentium.",
        price: 25000.0,
      },
    ],
  },
  {
    category: "أقراط",
    slug: "earrings",
    array: [
      {
        id: 1,
        imgName: "photo/earrings1.webp",
        title: "مفاتيح صغيرة مرصّعة بحجر موونستون",
        disc: " molestias magnam sed mollitia pariatur dicta illum.  ",
        price: 5500.0,
      },

      {
        id: 2,
        imgName: "photo/earrings2.webp",
        title: "قطرات كهرمان دافئة بنقوش شرقية",
        disc: " molestias magnam sed mollitia pariatur dicta illum.  ",
        price: 25000.0,
      },
      {
        new: "جديد",
        id: 3,
        imgName: "photo/earrings3.webp",
        title: " أصداف طبيعية مذهّبة بلمسة لؤلؤية",
        disc: " molestias magnam sed mollitia pariatur dicta illum.  ",
        price: 25000.0,
      },
      {
        id: 4,
        imgName: "photo/earrings4.webp",
        title: "تصميم ملوكي بقمّة حجر ياقوت أحمرs",
        disc: " molestias magnam sed mollitia pariatur dicta illum.  ",
        price: 25000.0,
      },
    ],
  },
  {
    category: "قلادة",
    slug: "necklace",
    array: [
      {
        id: 1,
        new: "جديد",
        imgName: "photo/necklace1.webp",
        title: "شلال سلاسل فضية بانسيابٍ حريري",
        disc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
        price: "4250,00",
      },
      {
        id: 2,
        imgName: "photo/necklace2.webp",
        title: "زخارف عربية تعانق حجر فيروزٍ معتّق",
        disc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
        price: "4250,00",
      },
      {
        id: 3,
        imgName: "photo/necklace3.webp",
        title: " قلب كريستالي يشرق بالدفء",
        disc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
        price: "4250,00",
      },
      {
        id: 4,
        imgName: "photo/necklace4.webp",
        title: "سلسلة رفيعة تحمل مفتاحاً صغيراً مرصَّعاً",
        disc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
        price: "4250,00",
      },
      {
        id: 5,
        new: "جديد",
        imgName: "photo/necklace5.webp",
        title: "حجر موونستون هلالي يؤطره الفضة السوداء",
        disc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
        price: "4250,00",
      },
    ],
  },
];
